### PR TITLE
make the AdlInstrumentTester a P-Impl

### PR DESCRIPTION
**Pull request by jpcima**
I will modify `AdlInstrumentTester` for the incoming bank work.
In C++ unfortunately, changing the fields of a class is an ABI breakage.
I am redesigning this class for P-Impl use to give it stable ABI; it's the same pattern that Qt libraries use.

### CODE REVIEW

**Comment by jpcima** [comment]
I don't understand how to use this command line. Have you used it yourself?

It looks for "-1" passed as bank number. But before, the function `is_number` is checking for `isdigit` on all the characters, which '-' is not. There has to be a problem here.

**Comment by Wohlstand** [comment]
You only need to feed any MIDI file (yes, it's a clunky API) and yes, put the -1 as a bank number, or even pass one of special flags... I forgot myself too... But I successfully ran the instrument testing once upon...

**Comment by Wohlstand** [comment]
The "atoi" must detect "-1" as it is designed for signed integers

**Comment by jpcima** [comment]
It responds to keys like it seems it should.
(this terminal UI however still displays like crap to me. It was already the case with Bisqwit ADLMIDI)

**Comment by Wohlstand** [comment]
The displayed crap was an old thing,  and yeah, why not to completely rework it? I mean make the whole UI of it to be more robust and beautiful? Anyway it's not so useful as this ADLMIDI2 is intended to match most of Bisquit's original in most. At me is also crap, and because of UI are strong lags on Windows due it's super slow console printing responsing

**Comment by jpcima** [comment]
I would like if there were a library which permits some TUI programming like curses, but at the same time which I could embed in JUCE graphics, and mix with normal drawn graphics.

It's not out of question that I derive a program from my current curses or JUCE interface, and I transform it into a MIDI player. I'll think more about this after completing the synthesizer work.

I like the Adlib Tracker, it's a nice use of terminal graphics for user interface.

**Comment by Wohlstand** [comment]
Anyway, I'll take this now

**Pull request merged**
