### PR TITLE
CMake cleanup

### PR DESCRIPTION
**Pull request by Flamefire**
Next round of improvements

More to come, but wanted to test CI first

### CODE REVIEW

**Comment by Flamefire** [comment]
@Wohlstand Can you add testing of the vlc plugin lib to CI?
BTW: Can the manual build files (projects, makefiles) be removed as you got CMake? Maintaining both is a hassle (out of experience)

**Comment by Wohlstand** [comment]
The VLC test is done on AppVeyor for now: https://ci.appveyor.com/project/Wohlstand/libadlmidi/builds/21032465/job/68lc8j0h2xr298f1
But yeah, I need to provide VLC test on Semaphore-CI, but, that doesn't looks hard, gonna to try some...

**Comment by Wohlstand** [comment]
Done, Semaphore-Ci now does libVLC build

**Comment by Wohlstand** [comment]
Anyway yeah, nuke autotools build of libVLC codec as it was kept for temporary until I have figured out how to correctly build VLC plugin from off CMake. :fox_face:

**Comment by Flamefire** [comment]
Ok done for now

**Comment by Wohlstand** [comment]
Gonna to provide DJGPP CI test...

**Comment by Wohlstand** [comment]
Made, I also have made macOS build too.

**Pull request merged**
