### PR TITLE
implement copy for OplChannel, and move implementations in .cpp

### PR DESCRIPTION
**Pull request by jpcima**
Same as in libOPNMIDI, including fixes added later

### CODE REVIEW

**Comment by Wohlstand** [comment]
I think, I'll wait when you will complete backporting your changes from https://github.com/Wohlstand/libOPNMIDI/pull/21 which is now works perfectly everywhere: opnmidiplay, VLC and phone!

**Comment by jpcima** [comment]
The backporting is all complete. I created this after the final fix of OPNMIDI.
Only tests are missing. You intend to have a copy a ADLMIDI too?

**Comment by Wohlstand** [comment]
Unit tests, I think, would be useful for ADLMIDI too, yeah, I created them on OPNMIDI as I caught a strong crash in it first and I had to debug a library on the phone

**Comment by Wohlstand** [comment]
Gotta to test this around...

**Comment by jpcima** [comment]
It's good to hear the things seem to work at last.
btw: your VLC plugin source is not compatible with my plugin API version. I think it has the code, but commented, and not updated to use `generateFormat`.

I wrote you an issue about huge RAM usage of catch unit tests.
Please consider. [OPNMIDI #19](https://github.com/Wohlstand/libOPNMIDI/issues/19)

**Comment by Wohlstand** [comment]
Just now tested this on my phone, and it works perfectly! :smile:

**Comment by Wohlstand** [comment]
> I wrote you an issue about huge RAM usage of catch unit tests.
Please consider. OPNMIDI#19

Yeah, catch-mini is a choice, even to just don't wait when super-heavey headers tonn will be pased when I really don't need to much crap which is dead code because of unusage. :smiley: 

> btw: your VLC plugin source is not compatible with my plugin API version. I think it has the code, but commented, and not updated to use generateFormat.

Yeah, as I needed to use `libvlc_version.h` and polish the support for newer VLC versions to let it work at you, I mean in VLC 3.0 and higher. My system has VLC 2. However, I built VLC3 from the sources, however, without of GUI, but I only needed for the library headers set and testing backend, so, I have that I needed :fox_face: :smile:

**Pull request merged**
