### PR TITLE
specialized hash table for bank number mappings

### PR DESCRIPTION
**Pull request by jpcima**
#59 

I create a hashmap container which is specialized for mapping things to bank numbers.
This replaces the current `BankMap`. A unit test is included.
This structure is optimized for worst case, because it's not only easier but also for RT reasons, and it allows for some cache locality (if it was reserved in one block).

The standard containers would not provide the functionality needed, because they do not allow to reserve storage for a fixed number of elements. I have a normal insertion which follows STL semantics, and a policy-based insertion which does not attempt to extend the storage.

Now, I am thinking about storing the instruments in this structure instead of having the indirection into instrument arrays of ADLMIDI. It's because the erasure operations are going to create holes, and the operations may require worst case in O(N). (and anyway, it will not be any worse than midiplay currently, which does its std::map lookup every NoteOn).

### CODE REVIEW

**Comment by Wohlstand** [comment]
Also, replacing of standard containers here would help me to check out the thing on Wattcom thing again, as previously I have built the thing, but it failed to work due strong bugs in a stack processing I had found while long research and analytics: https://github.com/open-watcom/open-watcom-v2/issues/391

**Comment by Wohlstand** [comment]
Damn! You forgot one thing that code must be in C++98 because of Android SDK and older compilers support

**Comment by Wohlstand** [comment]
So, now I trying to fix something by myself... And, std::unique_ptr I'll replace with existing custom-made pointer class I'll move into separate header for common usage in different headers

**Comment by Wohlstand** [comment]
And another thing, using of unique pointers is no way use the std::list container as it tries to use Copy constructor. I only can make it work as move constructur

**Comment by jpcima** [comment]
> as it tries to use Copy constructor

I don't think so. Values in a std::list do not have to be moved, unlike in std::vector in case of growth.

> Addition, removal and moving the elements within the list or across several lists does not invalidate the iterators or references. An iterator is invalidated only when the corresponding element is deleted.

**Comment by Wohlstand** [comment]
Okay, as now I'm tired, I have posted my small changes into "WIP-banks" branch you can pull to you.
What you need to do:
* Avoid in-class assignments, move them into constructor. C++11 allows that, but not C++98.
* Don't use any std::* smart pointers and use/polish custom-made shared pointer things.
* Don't use `nullptr`, use `NULL` with no matter to warnings. `nullptr` is C++11 only.
* I think, you better use something different from the std::list as unique pointer concept is not so good for that...

**Comment by jpcima** [comment]
I will put the compiler in std=c++98 and I'll fix everything. See ya.

**Pull request merged**
