### PR TITLE
Avoid home-grown integer types

### PR DESCRIPTION
**Pull request by Cacodemon345**
This is intended to fix compile errors on some operating systems.

### CODE REVIEW

**Comment by Wohlstand** [comment]
I made that as a workaround for older compiler toolchains that do lack them. They are required on older systems where they gets missing. You better change the condition to don't declare them when use modern systems and declare when using legacy

**Comment by Cacodemon345** [comment]
So we bake in the check for older systems in the CMake script? That should be possible.

**Comment by Wohlstand** [comment]
I mainly do check the presence of stdc macros which usually always exist and everywhere, and when they don't exist, or the C version is smaller than required, the hand-made integers getting defined. Also, I do use the C90 and C++98 standards (to ensure theb compatibility with older compilers) while I build the library, and those integers were absent at older standards.

**Comment by Wohlstand** [comment]
However, I left the check for the case a wopl library can be re-used by other projects also and they can better use this.

**Comment by Cacodemon345** [comment]
I still would argue going for the CMake path; it is easier to check whether the required symbols are actually defined that way.

**Comment by Cacodemon345** [comment]
I think I will do this PR at a later time.

**Pull request closed without merging**
