### PR TITLE
embedded bank loading API into multi-bank

### PR DESCRIPTION
**Pull request by jpcima**
Proposal to implement like suggested in #125. Not tried

### CODE REVIEW

**Comment by Wohlstand** [comment]
When embedded banks are disabled, you must to set play's error that this thing built without of embedded banks.

**Comment by Wohlstand** [comment]
Okay, because App-Get failed, I restarted the build, it must be fine now...
Also, I'll try to test this thing in work, it's very curious how it will work...

**Comment by jpcima** [comment]
Semaphore says it can have a cache of debian packages. (to use in place of apt-get)
https://semaphoreci.com/docs/how-to-install-dependency.html#caching-installations

**Comment by Wohlstand** [comment]
Oh, that would help a lot!

**Pull request merged**
