### PR TITLE
dosbox: fix a potential cache access problem

### PR DESCRIPTION
**Pull request by jpcima**
For some reason I rethought of last Dosbox changes, and came the "damn" moment about a mistake made.
As the cache entry is referred inside its vector container and the lock is released, it could be that another pushes to the vector near the same moment, invalidating the item's reference. It can do an invalid access after the line 1461.

Not a likely problem for sure, here is the fix.

### CODE REVIEW

**Comment by Wohlstand** [comment]
Huh?

**Comment by jpcima** [comment]
I made a mistake a mistake in the "fix". lol wait

**Comment by jpcima** [comment]
The thing is, it would need entries allocated by new, so the vector resized will not break references.
Then, I would like to have entries as RAII, so the library can load and unload clean. (plugin use)

Problem, c++ 98 does not have `shared_ptr`. Is `std::tr1::shared_ptr` ok to use?

**Comment by Wohlstand** [comment]
Then, you need to use hand-made one, like I have used on libADLMIDI side. This thing would be some sort of simplified but keep same RAII concept.

**Comment by jpcima** [comment]
I think of the current fix as fine, and fixed a warning along the way about the pthread mutex.
Built the file on gcc and clang with -Wall, both c++ 98 and 11 configurations.

**Comment by Wohlstand** [comment]
Then it's need to validate the build on official Android NDK to be sure this will work. The reason I don't use std::*ptr that Android NDK have lacked them.

**Comment by jpcima** [comment]
Oh I can check it. Which version?

**Comment by Wohlstand** [comment]
Primary, latest

**Comment by jpcima** [comment]
I picked ndk r18 with ARM. It built in both of c++98 or c++11, with either kind of ptr.
About this "arm 4.9" toolchain, I noted it contains a clang wrapper in place of g++, and has the STL substituted with llvm's.

`arm-linux-androideabi/bin/clang++ -std=c++11 -c dbopl.cpp`
`arm-linux-androideabi/bin/clang++ -std=c++98 -c dbopl.cpp`

**Comment by Wohlstand** [comment]
I hope, this will be built fine with any ABI, as my phone does using 32-bit ARM eabi-v7, let's check that...

**Comment by jpcima** [comment]
The ndk-16b arm platform was able to compile this based on gcc.
The latest had a problem starting a build of your player, because it lacks the mips64 target, removed from r17.

**Comment by Wohlstand** [comment]
Me at home now, which means, I'm able to test the stuff on a place now! :fox_face: :+1:

**Pull request merged**
